server:
  port: 10006 # 配置服务端口
spring:
  application:
    name: member-service-nacos-provider # 配置服务的名称，名字任意这里与项目名保持一致
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    # 别忘记创建数据库之后修改数据库名称
    url: jdbc:mysql://bj-cynosdbmysql-grp-71ax6pli.sql.tencentcdb.com:24169/e_commerce_center_db?useSSL=false&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: Ww*20021208002
# 配置naocs
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848 # 配置nacos的地址
# 暴露所有的监控点
management:
  endpoints:
    web:
      exposure:
        include: "*"
mybatis:
  mapper-locations: classpath:mapper/*.xml # 扫描所有Mapper.xml
  type-aliases-package: com.sun.springcloud.entity # 扫描所有实体类，可以直接使用类名来标识
