server:
  port: 10001 # 配置服务端口
spring:
  application:
    name: member-service-provider # 配置服务的名称，名字任意这里与项目名保持一致
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    # 别忘记创建数据库之后修改数据库名称
    url: jdbc:mysql://bj-cynosdbmysql-grp-71ax6pli.sql.tencentcdb.com:24169/e_commerce_center_db?useSSL=false&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: Ww*20021208002
  # 配置zipkin
  zipkin:
    base-url: http://127.0.0.1:9411 # 配置zipkin的地址，根据自己的实际情况配置
  sleuth:
    sampler:
      probability: 1.0 # 配置采样率，1.0表示全部采集
mybatis:
  mapper-locations: classpath:mapper/*.xml # 扫描所有Mapper.xml
  type-aliases-package: com.sun.springcloud.entity # 扫描所有实体类，可以直接使用类名来标识
eureka: # eureka客户端配置
  client:
    register-with-eureka: true # 将自己注册到eureka服务
    fetch-registry: true # 发现服务功能，如果是集群，必须要能发现服务才能配合ribben进行负载均衡
    service-url:
      # 需要注册到两个服务，则只需要用逗号间隔
      defaultZone: http://eureka9001.com:9001/eureka/, http://eureka9002.com:9002/eureka/  #表示自己要注册到哪个服务
